# Name : Atik Mandhat
# Enrollment No.: 20SOECE13017
# Class: CE-B
# Experiment: 18

In [15]:
import numpy as np

In [16]:
arr = np.array([
    [
        [1, 2, 3,4], [5, 6,7,8],[9,10,11,12]
    ], 
    [
        [13,14,15,16], [17,18, 19,20],[21, 22, 23,24],
    ]
])
print(arr)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
newarr=arr.ravel()
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

# 
# 1-Find the total EVEN numbers ADDITION from the given 3-D array.
# 


In [13]:
evensum=0
for item in newarr:
    if item%2==0:
        evensum =evensum+item
        print(f"Numb is {item}: {evensum}")
        
 
    

Numb is 2: 2
Numb is 4: 6
Numb is 6: 12
Numb is 8: 20
Numb is 10: 30
Numb is 12: 42
Numb is 14: 56
Numb is 16: 72
Numb is 18: 90
Numb is 20: 110
Numb is 22: 132
Numb is 24: 156


In [19]:
print(f"The sum of all Even Number ::: {evensum}")

The sum of all Even Number ::: 156


# 
# 2- Find the total ODD numbers ADDITION from the given 3-D array.
# 

In [21]:
oddsum=0
for item in newarr:
    if item%2==1:
        oddsum =oddsum+item
        print(f"Numb is {item}: {oddsum}")
        
 
    

Numb is 1: 1
Numb is 3: 4
Numb is 5: 9
Numb is 7: 16
Numb is 9: 25
Numb is 11: 36
Numb is 13: 49
Numb is 15: 64
Numb is 17: 81
Numb is 19: 100
Numb is 21: 121
Numb is 23: 144


In [23]:
print(f"The sum of all Odd Number ::: {oddsum}")

The sum of all Odd Number ::: 144


# 5) Create a Numpy array filled with all zeros with the shape of (5,5)

In [3]:
zeros=

NameError: name 'np' is not defined