# Name : Atik Mandhat
# Enrollment No.: 20SOECE13017
# Class: CE-B
# Experiment: 17


# 1) Create a 1D array.


In [1]:
import numpy as np

In [26]:
oneD = np.random.rand(10)
oneD.shape

(10,)

# 2) Create a 2D array with the shape of (3,3)

In [35]:
twoD=np.random.rand(3,3)
twoD.shape


(3, 3)


# 3) Create a 3D array with the shape of (2,3,4)



In [38]:
threeoD=np.random.rand(2,3,4)
threeoD.shape


(2, 3, 4)

# 4) Create a boolean array with the shape of (4,4)

In [54]:
arr=np.arange(-4,12).reshape(4,4)
b=np.array([arr],bool)
b
# arr

array([[[ True,  True,  True,  True],
        [False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

# 5) Create a Numpy array filled with all zeros with the shape of (5,5)

In [57]:
zeros=np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 6) Create a Numpy array filled with all ones with the shape of (5,5)

In [62]:
ones=np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])